---
abstract: 'Specify implicit prerequisites directly in your Perl code'
author:
  - 'Van de Bugger <van.de.bugger@gmail.com>'
build_requires:
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Perl::PrereqScanner: '0'
  Test::Deep: '0'
  Test::DiagINC: '0.002'
  Test::Fatal: '0'
  Test::More: '0'
  Test::Routine: '0'
  Test::Routine::Util: '0'
  blib: '1.01'
  if: '0'
  lib: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.040, CPAN::Meta::Converter version 2.150001'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-PrereqScanner-Scanner-Hint
provides:
  Perl::PrereqScanner::Scanner::Hint:
    file: lib/Perl/PrereqScanner/Scanner/Hint.pm
    version: v0.1.0
requires:
  Module::Runtime: '0'
  Moose: '0'
  Perl::PrereqScanner::Scanner: '0'
  Try::Tiny: '0'
  namespace::autoclean: '0'
  perl: '5.006'
  version: '0.77'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Perl-PrereqScanner-Scanner-Hint
  homepage: https://metacpan.org/release/Perl-PrereqScanner-Scanner-Hint
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://vandebugger.fedorapeople.org/hg/perl-Perl-PrereqScanner-Scanner-Hint
version: v0.1.0
